### ISSUE TITLE
Polished tree shaking

### ISSUE THREAD

**Issue by mrcnk** [sodify/insites-ui#21]
Polished module, which we use for `rgba`, `lighten` and other mixins for `styled-components` doesn't tree-shake too good out of the box, what results in bloated bundle size of our lib.
There's an article dedicated to that:
https://iamakulov.com/notes/polished-webpack/
And recently opened issue in Polished:
https://github.com/styled-components/polished/issues/478
We should investigate what we can do about it.
Our bundle analysis: https://bundlephobia.com/result?p=insites-ui@0.2.7

**Comment by rago4** [comment]
This should solve the problem 👉 https://github.com/sodify/insites-ui/pull/23

**Comment by mrcnk** [comment]
Thanks, looks better
https://bundlephobia.com/result?p=insites-ui@0.2.8
